(source (official cli))
(config username "Danny Martini")
(config project_name ls)
(config npm_username despairblue)
(config github_username despairblue)
(config project_description "lists the current directory")
(config package_manager Esy)
(config ci_cd Github)
(config syntax Reason)
(config project_snake ls)
(config project_slug ls)
(config test_framework Rely)
